vercel/pkg

- lib/index.js
- lib/packer.js
- lib/producer.js
- prelude/bootstrap.js
- test/utils.js
I just trying to understand the code and found this typos.
> Typos + simplify code

- lib/index.js
> Show version before compilation

- package.json
This also fixes installing from git
> Use prepare instead of deprecated prepublish

- dictionary/logform.js
- test/test-79-npm/logform/logform.js
- test/test-79-npm/logform/package.json
there are some kind of combination of formats that requires a library called logform.
I added its dependency as a new dictionary.
Thanks.
(i closed the old PR and opened a new one. sorry for the mess)
> logform support (winstonjs library)

- prelude/bootstrap.js
Fixes https://github.com/zeit/pkg/issues/467
> Use internalModuleReadJSON where it is defined.

- prelude/bootstrap.js
- test/test-50-fs-runtime-layer-2/main.js
> readdir-options

- README.md
Fixed some grammar and sentence structure to improve readability and comprehension.
> Fixed grammar and sentence structure

- lib/detector.js
> Add support for native bigint parsing

- README.md
> Branding change

- README.md
Ref https://github.com/vercel/pkg-fetch/pull/67
> docs: MAKE_JOB_COUNT and PKG_IGNORE_TAG env var

- package.json
- yarn.lock
No need to run tests before publishing if we ensure they pass on PRs.
> Update release script.

- README.md
I admit it's a bit wordy. But I figured this could be a big trade off for some users, so it may need some explanation.
> Add section about bytecode flag to README.md

- test/test-50-fs-runtime-layer-2/main.js
Fixes test after nodejs/node@9c06103 .
> test-50-fs-runtime-layer-2: remove unnecessary assertion on hint

- lib/producer.ts
Pick #1161 with some trivial changes. 
See https://github.com/vercel/pkg/pull/1161#issuecomment-854080249 . 
cc: @mojoaxel
> producer: improve readability and remove backed up native addon at the end

- lib/detector.ts
> fix: catch babel parse errors

- package.json
- yarn.lock
> Bump to vercel/pkg-fetch@v3.2.6

- prelude/bootstrap.js
- test/test-1505/.gitignore
- test/test-1505/main.js
- test/test-1505/package.json
- test/test-1505/stat.js
See https://github.com/vercel/pkg/issues/1505#issuecomment-1034577651
> fix: fs.stat/fstat promises

- package.json
- yarn.lock
https://github.com/vercel/pkg-fetch/releases/tag/v3.3
> Bump to vercel/pkg-fetch@v3.3.0

- lib/detector.ts
- lib/index.ts
- lib/refiner.ts
- lib/walker.ts
- prelude/bootstrap.js
- test/test-50-ast-parsing-2/test-x-index.js
- test/test-50-global-object/test-y-resolve-A.js
- test/test-50-global-object/test-y-resolve-B.js
- test/test-50-many-arrow-functions/test-z-creator.js
- test/test-50-many-callbacks/test-z-creator.js
- test/test-79-npm/mongoose/mongoose.js
- test/test-80-compression-various-file-access/test_with_new_fs_promises.js
Lint is passing locally for me, hopefully it passes in CI as well
> chore: clean up obsolete eslint disable comments

- test/test-99-#1192/main.js
> style: fix typo in test-99-#1192/main.js

- package.json
Updated prebuild-install version from 6.1.4 to 7.1.1
> chore: bump prebuild-install@7.1.1

- prelude/bootstrap.js
In combination with https://github.com/vercel/pkg-fetch/pull/274, this adds support for node 19.6
> feat: support node v19
