- readme.md
See if repo dependencies are up-to-date at a glance. Also checks known security vunerabilities via [nodesecurity.io](https://nodesecurity.io).
> Add david-dm dependency shields to README

- dictionary/bunyan.js
- test/test-79-npm/bunyan/bunyan.js
- test/test-79-npm/bunyan/package.json
> dictionary: bunyan

- package-lock.json
- package.json
There is a warning when I install the pkg.
```
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning pkg > chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 14.91s.
```
```
$ npm install chalk@2.1.0
```
> chore(chalk): bump version

- .gitignore
- examples/express/package.json
- examples/express/readme.md
**The Issue**
Currently, following the instructions provided in the `README` result in `pkg` failing to build the executable. The error output references `node7` as being an undefined `target` in `package.json`.
**The Solution**
`pkg` relies on `pkg-fetch` for retrieving Node versions to be used as `targets` in building executables. As of `pkg-fetch` v2.5, no `node` v7.x.x is listed as an available source. Changing `node7` to `node10` fixes this issue as it is available via `pkg-fetch` v2.5.
**Additionally, this PR**
- Adds files/folders to .gitignore related to the example express app which should not be included in master.
- Improves README ducumentation for example express app.
> Fix pkg example express app

- README.md
This PR adds a disclaimer to the README, advising users that `pkg` is not required to use ZEIT Now.
> Add ZEIT Now Disclaimer

- README.md
This change should stop the NPM site from displaying 'Not Secure' due to an image being loaded over HTTP, not HTTPs.
> Load image over HTTPs

- dictionary/node-notifier.js
- package.json
- yarn.lock
Update configuration for *node-notifier*@>=6.0.0 (latest being 9.0.0, and this PR also fixes shipping with those latest versions).
See changes in https://github.com/mikaelbr/node-notifier/commit/54ddb7fe47856cc7dbea6d7abd4e7a6dfbeeeb5f.
As mentioned in [npm documentation](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies), peer dependencies are no longer installed by default. So I used it to constrain the supported version of *node-notifier*
> Fix configuration for node-notifier

- README.md
Added documentation about possibles error having the `NODE_OPTIONS` variable in the environment.
Related to issue [954](https://github.com/vercel/pkg/issues/954).
> Added documentation about NODE_OPTIONS 

- prelude/bootstrap.js
The PR is inspired by https://github.com/vercel/pkg-fetch/pull105#issuecomment-757116069
This is a pre-requisite for updating to newer Node.js version (currently supports only v12, v14 and for future usage >=v15). The change should preserver backward-compatibility.
Related: #1008 https://github.com/vercel/pkg-fetch/issues/114
> Support newer node versions which changed internalModuleReadJSON

- .eslintrc
- .gitignore
- lib/bin.js
- lib/detector.js
- lib/fabricator.js
- lib/follow.js
- lib/help.js
- lib/index.js
- lib/log.js
- lib/packer.js
- lib/producer.js
- lib/refiner.js
- lib/walker.js
- package.json
- prelude/bootstrap.js
- prelude/common.js
- yarn.lock
Moving to standardized tooling and configs. Turned off rules that clashed with how the code is currently written.
This PR should be merged after #1076
> Upgrade eslint + move to eslint-config-airbnb-base

- README.md
- lib/follow.js
- lib/index.js
- lib/packer.js
- lib/producer.js
- lib/refiner.js
- lib/walker.js
- prelude/bootstrap.js
- prelude/common.js
- prelude/diagnostic.js
- test/test-10-pnpm/.gitignore
- test/test-10-pnpm/main.js
- test/test-10-pnpm/package.json
- test/test-10-pnpm/test.js
- test/test-11-pnpm/.gitignore
- test/test-11-pnpm/main.js
- test/test-11-pnpm/package.json
- test/test-11-pnpm/test.js
- test/test-50-many-arrow-functions/test-z-creator.js
- test/test-50-many-callbacks/test-z-creator.js
- test/test-79-npm/cron/cron.js
- test/test-79-npm/ejs/ejs.js
- test/test.js
Add a mechanism to follow and track symlinks, making `pkg` work with PNPM and also package installed with `npm link` inside your `node_modules` folder.
Closes https://github.com/vercel/pkg/issues/941.
> Add support for symlink and pnpm.

- prelude/bootstrap.js
- test/test-1120-mkdir-mountpoints/main.js
- test/test-1120-mkdir-mountpoints/test-x-index.js
I'm working on a CLI tool that bundles some code, but then mirrors the directory structure out to the filesystem. This is done using mountpoints and this patch that allows `fs.mkdir` to apply to them.
> Support mkdir at mountpoints

- README.md
- lib/help.ts
- lib/walker.ts
As it turns out, not including bytecode is broken for modules that have a licenses array in their package.json.
One example of this is `utils-merge` which is a dependency of `express`.
Without this check, `license` will become undefined since there's no `type` property on that array.
This causes the module to be listed as non-public which means that it doesn't get included as CONTENT
That in turn triggers the exception when building without bytecode.
Anyways, this was not fun to debug, because there's no mention anywhere of this isPublic check.
> Fix isPublic check for licenses array

- lib/index.ts
Currently `pkg` can't generate executable for different arch:
> Warning Failed to make bytecode node14-arm64 for file ...
as it attempts to run Node of different arch to make bytecode.
We can set up QEMU and binfmt to allow emulation. However, the "linux"
binary needs libraries from the system, and it is PITA to set up the
entire sysroot of a different arch.
This change workarounds the issue by using "linuxstatic" to generate
bytecode for different arch.
> Use "linuxstatic" to generate bytecode for different arch on Linux

- lib/index.ts
- lib/mach-o.ts
Inspired by dotnet/runtime#46558 .
Test: manual, Apple M1 (with [mandatory code signing requirement](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes))
```zsh
Θ pkg -t node14-mac-arm64 . 
> pkg@5.1.0
> Warning Cannot resolve 'config'
/Users/jc/Sources/pkg/lib-es5/index.js
Dynamic require may fail at run time, because the requested file
is unknown at compilation time and not included into executable.
Use a string literal as an argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option.
> Warning Cannot find module 'internal/util' from '/Users/jc/Sources/pkg/prelude'  in /Users/jc/Sources/pkg/prelude/bootstrap.js
> Warning Cannot find module 'internal/module' from …
```
> feature: allow macOS code signing by including payload in str table

- lib/index.ts
```
> Warning Unable to sign the macOS executable on non-macOS host
Due to the mandatory code signing requirement, before the
executable is distributed to end users, it must be signed with
the "codesign" utility of macOS, otherwise, it will be immediately
killed by kernel on launch. An ad-hoc signature is sufficient.
To do that, "codesign --sign - <executable>" on a Mac.
```
Ref: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes
See also: golang/go#42684
> Add a warning about the macOS mandatory code signing requirement

- package.json
- yarn.lock
- Use Docker to build binaries for linux-arm64 (vercel/pkg-fetch#191)
- Enable LTO for macOS binaries (vercel/pkg-fetch#192)
- Bump to Node v16.3.0 (vercel/pkg-fetch#196)
- Add support for linuxstatic-armv7 platform* (vercel/pkg-fetch#194, @Hypfer)
\* best-effort basis, not semver-protected.
> Bump to vercel/pkg-fetch@v3.2.1

- README.md
- lib/index.ts
- lib/mach-o.ts
ldid is a "codesign"-like open source utility to sign Darwin (macOS/iOS) executable or package.
It is possible to run ldid on Linux.
Bug: #1251
> Allow to fallback to "ldid" for macOS ad-hoc signing

- prelude/bootstrap.js
When a `.node` file is required `pkg` copies it in a temporary folder like `/tmp/<hash>/addon.node` the problem is that for modules like `sharp` this isn't working as them are statically linked to other `.so` files using relative paths. This pr will copy the entire module folder inside the temporary directory, this allows also to remove the `tryImport` function as there is no reason to try again if that fails. 
I tested this on my end and it's working
I also grouped all hash folders inside `pkg` folder to be sure that the copy will run when users will update pkg, otherwise the copy may not be done when the folder already exists but was created with a previous pkg version
cc @jesec @leerob @erossignon 
Fixes #1075
> fix: better support of `.node` files

- prelude/bootstrap.js
When tring to import a file with `dlopen` and it's not inside snapshot regex could fail and throw error
Fixes #1319
> bootstrap: skip regex when dlopen path isn't inside snapshot

- lib/walker.ts
This PR adds support for pkg to identify any built-in/core module that's being imported using the `node:` protocol.
This would fix fix #1309.
This would also fix #1363.
> Add support for `node:` protocol

- prelude/bootstrap.js
We have an issue reported by several users showing error message “Error: The specified module could not be found.” where some .node files cannot be found in Temp folder under Windows. Because of this error, application cannot be started.
After analysis we have seen that the directories inside temp remain but files are cleaned up (we don’t know which clean up mechanism, Windows OS or antivirus software but we anyway have no means to intervene here). pkg currently only checks for existence of the folder pkg/<hash> and if exists, no copying is done. Since one can never be sure about what happens with files and directories in temporary folder when the application is not active, safer way would be to always do the copying.
> Copy module folders always to temporary folder

- prelude/bootstrap.js
Make sure to copy the .node file in the temporary folder before trying
to dlopen it.
> fix: usage of .node files not in node_modules

- package.json
While using the pkg API in a typescript project, my editor complained it cannot find the declaration file for pkg. This PR add just the needed declaration file for the API so that the warning mentioned goes away.
> feat: add simple type export (TS)

- lib/walker.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> chore: replace deprecated String.prototype.substr()

- lib/packer.ts
The `bytecode` CLI flag is specified as a boolean option in the
arguments passed to `minimist`.
My formatter also removed a useless trailing space in the same file...
> fix: `bytecode` option is a boolean

- prelude/bootstrap.js
This can happen when two processes try to load the same .node file.
> fix: do not overwrite temp .node files

- test/test-10-pnpm/main.js
- test/test-11-pnpm/main.js
- test/test-12-compression-node-opcua/main.js
- test/utils.js
Tests on node 12 are failing because pnpm requires `node >= 14.19`.
> fix broken tests on node 12; latest pnpm requires node >= 14.19

- prelude/bootstrap.js
This PR fixes [#1589](https://github.com/vercel/pkg/issues/1589). The fix has two effects:
1. `.node` files that must exist on the real filesystem instead of the virtual snapshot filesystem (because of process.dlopen) are only copied if they do not exist. If they already exist then it doesn't matter anymore whether they are currently opened by an running instance of the pkg-packaged app or not, because existing files are untouched now.
2. The start of the pkg app a second, third, etc. time is as fast as with pkg 5.5.2 again since (in best case) no copy action takes place
> fix(boootstrap): prevent to override existing node addon file

- lib/detector.ts
- package.json
- typings/babel__generator.d.ts
- yarn.lock
Allow new ECMAScript features by default.
Support language features supported by the latest version of Node.js supported, instead of the oldest. 
pkg only uses Babel to parse dependencies. It does NOT transform users' sources. It is the users' responsibility to make sure that their code can run on the target Node.js version. 
https://babeljs.io/docs/en/babel-parser#latest-ecmascript-features
Refs: https://github.com/vercel/pkg/pull/1249#issuecomment-1111543386
Closes: #1249, #1645
> detector: use Babel AST and default plugins

- lib/producer.ts
Don't pass "--target" if the package uses N-API.
Bug: #1695
> producer: properly call "prebuild-install" if N-API is used

- .github/workflows/ci.yml
- README.md
- lib/index.ts
- test/test-50-bakery-fetch/main.js
- test/test-50-corrupt-executable/main.js
- test/test-50-no-signature/main.js
- test/test-50-no-signature/test-x-index.js
- test/test-50-reproducible/main.js
There are scenarios where one would want to sign manually or later the binaries.
I'm adding a simple option that will skip the final codesign on macos.
> feat: add option to skip signature on macos

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_regression.yml
- .github/workflows/ci.yml
- README.md
- lib/help.ts
- package.json
As per #1886, here is a PR to drop support for 12 which is EOL and 14 which is EOL in a month.
As some users may rely on those versions, this should be included in a major release.
> chore: remove eol nodejs in tests

- dictionary/tesseract.js.js
- test/test-79-npm/tesseract.js/tesseract.js.js
Test will still fail due to #1863, but at least it _should_ be correct if/when it's fixed.
> test: update tesseract.js test for v4

- test/utils.js
according error message of the actions and https://github.com/pnpm/pnpm/issues/6297
> Ignore pnpm test for node14

- package.json
- yarn.lock
To use the newest versions of Node.js, we need to upgrade `pkg-fetch` ([GitHub Release](https://github.com/vercel/pkg-fetch/releases/tag/v3.5), [npm](https://www.npmjs.com/package/pkg-fetch))
> Upgrade pkg-fetch to 3.5.2

- prelude/bootstrap.js
In my project, I noticed that a library that used `isCharacterDevice` on a file from the snapshot crashed. This adds the missing functions as noops (and I made isFIFO use noop so it was clearer).
I thought about making these mirror their files that were included, but I don't think either makes sense within the virtual fs. Please correct me if I'm wrong.
> fix: Add missing functions from restored fs.Stats

- prelude/bootstrap.js
- test/test-99-#1861/index.js
- test/test-99-#1861/launch.bat
- test/test-99-#1861/main.js
There is a bug that occurs when a packaged executable (Windows 11) is launched from a child process which was created by the executable itself (like for a self updating executable). This bug was reported already in #1861.
It seems that there is a conditional block at the start of `bootstrap.js` which has the potential to cause `ENTRYPOINT` to become `undefined`. I have to admit that I don't understand the purpose of the that specific code block, but I understand as much as that there always needs to be an entrypoint to successfully launch the executable. So I simply added an `else` statement as a fall back to the `DEFAULT_ENTRYPOINT`.
> fix: missing entrypoint when launched from self-created child process
